GET http://localhost:3333/

###
POST http://localhost:3333/restaurant
Content-Type: application/json

{
    name: "FSW Donalds",
    slug: "fsw-donalds",
    description: "O melhor fast food do mundo",
    avatarImageUrl:"https://u9a6wmr3as.ufs.sh/f/jppBrbk0cChQvcNP9rHlEJu1vCY5kLqzjf29HKaeN78Z6pRy",
    coverImageUrl:"https://u9a6wmr3as.ufs.sh/f/jppBrbk0cChQac8bHYlkBUjlHSKiuseLm2hIFzVY0OtxEPnw",
}
